# Generated by Django 2.1.7 on 2019-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='Amount',
        ),
        migrations.AddField(
            model_name='donor',
            name='total_amount',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
