# Generated by Django 2.1.7 on 2019-03-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WomanNeedsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='women/photos/%Y/%m/%d')),
                ('about_me', models.TextField()),
                ('skills', models.TextField()),
                ('linkedIn', models.CharField(max_length=250)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WomanNeedsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='women/photos/%Y/%m/%d')),
                ('about_me', models.TextField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('requirements', models.TextField()),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('percentage_funded', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
